export type Country = {
  code: string;
  name: string;
  flag: string;
  phoneCode: string;
  abbreviation?: string;
};

export const COUNTRIES: Country[] = [
  { code: 'af', name: 'Afghanistan', flag: '🇦🇫', phoneCode: '+93' },
  { code: 'al', name: 'Albania', flag: '🇦🇱', phoneCode: '+355' },
  { code: 'dz', name: 'Algeria', flag: '🇩🇿', phoneCode: '+213' },
  { code: 'ad', name: 'Andorra', flag: '🇦🇩', phoneCode: '+376' },
  { code: 'ao', name: 'Angola', flag: '🇦🇴', phoneCode: '+244' },
  { code: 'ag', name: 'Antigua and Barbuda', flag: '🇦🇬', phoneCode: '+1-268' },
  { code: 'ar', name: 'Argentina', flag: '🇦🇷', phoneCode: '+54' },
  { code: 'am', name: 'Armenia', flag: '🇦🇲', phoneCode: '+374' },
  { code: 'au', name: 'Australia', flag: '🇦🇺', phoneCode: '+61' },
  { code: 'at', name: 'Austria', flag: '🇦🇹', phoneCode: '+43' },
  { code: 'az', name: 'Azerbaijan', flag: '🇦🇿', phoneCode: '+994' },
  { code: 'bs', name: 'Bahamas', flag: '🇧🇸', phoneCode: '+1-242' },
  { code: 'bh', name: 'Bahrain', flag: '🇧🇭', phoneCode: '+973' },
  { code: 'bd', name: 'Bangladesh', flag: '🇧🇩', phoneCode: '+880' },
  { code: 'bb', name: 'Barbados', flag: '🇧🇧', phoneCode: '+1-246' },
  { code: 'by', name: 'Belarus', flag: '🇧🇾', phoneCode: '+375' },
  { code: 'be', name: 'Belgium', flag: '🇧🇪', phoneCode: '+32' },
  { code: 'bz', name: 'Belize', flag: '🇧🇿', phoneCode: '+501' },
  { code: 'bj', name: 'Benin', flag: '🇧🇯', phoneCode: '+229' },
  { code: 'bt', name: 'Bhutan', flag: '🇧🇹', phoneCode: '+975' },
  { code: 'bo', name: 'Bolivia', flag: '🇧🇴', phoneCode: '+591' },
  { code: 'ba', name: 'Bosnia and Herzegovina', flag: '🇧🇦', phoneCode: '+387' },
  { code: 'bw', name: 'Botswana', flag: '🇧🇼', phoneCode: '+267' },
  { code: 'br', name: 'Brazil', flag: '🇧🇷', phoneCode: '+55' },
  { code: 'bn', name: 'Brunei', flag: '🇧🇳', phoneCode: '+673' },
  { code: 'bg', name: 'Bulgaria', flag: '🇧🇬', phoneCode: '+359' },
  { code: 'bf', name: 'Burkina Faso', flag: '🇧🇫', phoneCode: '+226' },
  { code: 'bi', name: 'Burundi', flag: '🇧🇮', phoneCode: '+257' },
  { code: 'cv', name: 'Cabo Verde', flag: '🇨🇻', phoneCode: '+238' },
  { code: 'kh', name: 'Cambodia', flag: '🇰🇭', phoneCode: '+855' },
  { code: 'cm', name: 'Cameroon', flag: '🇨🇲', phoneCode: '+237' },
  { code: 'ca', name: 'Canada', flag: '🇨🇦', phoneCode: '+1' },
  { code: 'cf', name: 'Central African Republic', flag: '🇨🇫', phoneCode: '+236' },
  { code: 'td', name: 'Chad', flag: '🇹🇩', phoneCode: '+235' },
  { code: 'cl', name: 'Chile', flag: '🇨🇱', phoneCode: '+56' },
  { code: 'cn', name: 'China', flag: '🇨🇳', phoneCode: '+86' },
  { code: 'co', name: 'Colombia', flag: '🇨🇴', phoneCode: '+57' },
  { code: 'km', name: 'Comoros', flag: '🇰🇲', phoneCode: '+269' },
  { code: 'cd', name: 'Congo (DRC)', flag: '🇨🇩', phoneCode: '+243' },
  { code: 'cg', name: 'Congo (Republic)', flag: '🇨🇬', phoneCode: '+242' },
  { code: 'cr', name: 'Costa Rica', flag: '🇨🇷', phoneCode: '+506' },
  { code: 'ci', name: 'Côte d\'Ivoire', flag: '🇨🇮', phoneCode: '+225' },
  { code: 'hr', name: 'Croatia', flag: '🇭🇷', phoneCode: '+385' },
  { code: 'cu', name: 'Cuba', flag: '🇨🇺', phoneCode: '+53' },
  { code: 'cy', name: 'Cyprus', flag: '🇨🇾', phoneCode: '+357' },
  { code: 'cz', name: 'Czech Republic', flag: '🇨🇿', phoneCode: '+420' },
  { code: 'dk', name: 'Denmark', flag: '🇩🇰', phoneCode: '+45' },
  { code: 'dj', name: 'Djibouti', flag: '🇩🇯', phoneCode: '+253' },
  { code: 'dm', name: 'Dominica', flag: '🇩🇲', phoneCode: '+1-767' },
  { code: 'do', name: 'Dominican Republic', flag: '🇩🇴', phoneCode: '+1-809' },
  { code: 'ec', name: 'Ecuador', flag: '🇪🇨', phoneCode: '+593' },
  { code: 'eg', name: 'Egypt', flag: '🇪🇬', phoneCode: '+20' },
  { code: 'sv', name: 'El Salvador', flag: '🇸🇻', phoneCode: '+503' },
  { code: 'gq', name: 'Equatorial Guinea', flag: '🇬🇶', phoneCode: '+240' },
  { code: 'er', name: 'Eritrea', flag: '🇪🇷', phoneCode: '+291' },
  { code: 'ee', name: 'Estonia', flag: '🇪🇪', phoneCode: '+372' },
  { code: 'sz', name: 'Eswatini', flag: '🇸🇿', phoneCode: '+268' },
  { code: 'et', name: 'Ethiopia', flag: '🇪🇹', phoneCode: '+251' },
  { code: 'fj', name: 'Fiji', flag: '🇫🇯', phoneCode: '+679' },
  { code: 'fi', name: 'Finland', flag: '🇫🇮', phoneCode: '+358' },
  { code: 'fr', name: 'France', flag: '🇫🇷', phoneCode: '+33' },
  { code: 'ga', name: 'Gabon', flag: '🇬🇦', phoneCode: '+241' },
  { code: 'gm', name: 'Gambia', flag: '🇬🇲', phoneCode: '+220' },
  { code: 'ge', name: 'Georgia', flag: '🇬🇪', phoneCode: '+995' },
  { code: 'de', name: 'Germany', flag: '🇩🇪', phoneCode: '+49' },
  { code: 'gh', name: 'Ghana', flag: '🇬🇭', phoneCode: '+233' },
  { code: 'gr', name: 'Greece', flag: '🇬🇷', phoneCode: '+30' },
  { code: 'gd', name: 'Grenada', flag: '🇬🇩', phoneCode: '+1-473' },
  { code: 'gt', name: 'Guatemala', flag: '🇬🇹', phoneCode: '+502' },
  { code: 'gn', name: 'Guinea', flag: '🇬🇳', phoneCode: '+224' },
  { code: 'gw', name: 'Guinea-Bissau', flag: '🇬🇼', phoneCode: '+245' },
  { code: 'gy', name: 'Guyana', flag: '🇬🇾', phoneCode: '+592' },
  { code: 'ht', name: 'Haiti', flag: '🇭🇹', phoneCode: '+509' },
  { code: 'hn', name: 'Honduras', flag: '🇭🇳', phoneCode: '+504' },
  { code: 'hu', name: 'Hungary', flag: '🇭🇺', phoneCode: '+36' },
  { code: 'is', name: 'Iceland', flag: '🇮🇸', phoneCode: '+354' },
  { code: 'in', name: 'India', flag: '🇮🇳', phoneCode: '+91' },
  { code: 'id', name: 'Indonesia', flag: '🇮🇩', phoneCode: '+62' },
  { code: 'ir', name: 'Iran', flag: '🇮🇷', phoneCode: '+98' },
  { code: 'iq', name: 'Iraq', flag: '🇮🇶', phoneCode: '+964' },
  { code: 'ie', name: 'Ireland', flag: '🇮🇪', phoneCode: '+353' },
  { code: 'il', name: 'Israel', flag: '🇮🇱', phoneCode: '+972' },
  { code: 'it', name: 'Italy', flag: '🇮🇹', phoneCode: '+39' },
  { code: 'jm', name: 'Jamaica', flag: '🇯🇲', phoneCode: '+1-876' },
  { code: 'jp', name: 'Japan', flag: '🇯🇵', phoneCode: '+81' },
  { code: 'jo', name: 'Jordan', flag: '🇯🇴', phoneCode: '+962' },
  { code: 'kz', name: 'Kazakhstan', flag: '🇰🇿', phoneCode: '+7' },
  { code: 'ke', name: 'Kenya', flag: '🇰🇪', phoneCode: '+254' },
  { code: 'ki', name: 'Kiribati', flag: '🇰🇮', phoneCode: '+686' },
  { code: 'kp', name: 'North Korea', flag: '🇰🇵', phoneCode: '+850' },
  { code: 'kr', name: 'South Korea', flag: '🇰🇷', phoneCode: '+82' },
  { code: 'kw', name: 'Kuwait', flag: '🇰🇼', phoneCode: '+965' },
  { code: 'kg', name: 'Kyrgyzstan', flag: '🇰🇬', phoneCode: '+996' },
  { code: 'la', name: 'Laos', flag: '🇱🇦', phoneCode: '+856' },
  { code: 'lv', name: 'Latvia', flag: '🇱🇻', phoneCode: '+371' },
  { code: 'lb', name: 'Lebanon', flag: '🇱🇧', phoneCode: '+961' },
  { code: 'ls', name: 'Lesotho', flag: '🇱🇸', phoneCode: '+266' },
  { code: 'lr', name: 'Liberia', flag: '🇱🇷', phoneCode: '+231' },
  { code: 'ly', name: 'Libya', flag: '🇱🇾', phoneCode: '+218' },
  { code: 'li', name: 'Liechtenstein', flag: '🇱🇮', phoneCode: '+423' },
  { code: 'lt', name: 'Lithuania', flag: '🇱🇹', phoneCode: '+370' },
  { code: 'lu', name: 'Luxembourg', flag: '🇱🇺', phoneCode: '+352' },
  { code: 'mg', name: 'Madagascar', flag: '🇲🇬', phoneCode: '+261' },
  { code: 'mw', name: 'Malawi', flag: '🇲🇼', phoneCode: '+265' },
  { code: 'my', name: 'Malaysia', flag: '🇲🇾', phoneCode: '+60' },
  { code: 'mv', name: 'Maldives', flag: '🇲🇻', phoneCode: '+960' },
  { code: 'ml', name: 'Mali', flag: '🇲🇱', phoneCode: '+223' },
  { code: 'mt', name: 'Malta', flag: '🇲🇹', phoneCode: '+356' },
  { code: 'mh', name: 'Marshall Islands', flag: '🇲🇭', phoneCode: '+692' },
  { code: 'mr', name: 'Mauritania', flag: '🇲🇷', phoneCode: '+222' },
  { code: 'mu', name: 'Mauritius', flag: '🇲🇺', phoneCode: '+230' },
  { code: 'mx', name: 'Mexico', flag: '🇲🇽', phoneCode: '+52' },
  { code: 'fm', name: 'Micronesia', flag: '🇫🇲', phoneCode: '+691' },
  { code: 'md', name: 'Moldova', flag: '🇲🇩', phoneCode: '+373' },
  { code: 'mc', name: 'Monaco', flag: '🇲🇨', phoneCode: '+377' },
  { code: 'mn', name: 'Mongolia', flag: '🇲🇳', phoneCode: '+976' },
  { code: 'me', name: 'Montenegro', flag: '🇲🇪', phoneCode: '+382' },
  { code: 'ma', name: 'Morocco', flag: '🇲🇦', phoneCode: '+212' },
  { code: 'mz', name: 'Mozambique', flag: '🇲🇿', phoneCode: '+258' },
  { code: 'mm', name: 'Myanmar', flag: '🇲🇲', phoneCode: '+95' },
  { code: 'na', name: 'Namibia', flag: '🇳🇦', phoneCode: '+264' },
  { code: 'nr', name: 'Nauru', flag: '🇳🇷', phoneCode: '+674' },
  { code: 'np', name: 'Nepal', flag: '🇳🇵', phoneCode: '+977' },
  { code: 'nl', name: 'Netherlands', flag: '🇳🇱', phoneCode: '+31' },
  { code: 'nz', name: 'New Zealand', flag: '🇳🇿', phoneCode: '+64' },
  { code: 'ni', name: 'Nicaragua', flag: '🇳🇮', phoneCode: '+505' },
  { code: 'ne', name: 'Niger', flag: '🇳🇪', phoneCode: '+227' },
  { code: 'ng', name: 'Nigeria', flag: '🇳🇬', phoneCode: '+234' },
  { code: 'mk', name: 'North Macedonia', flag: '🇲🇰', phoneCode: '+389' },
  { code: 'no', name: 'Norway', flag: '🇳🇴', phoneCode: '+47' },
  { code: 'om', name: 'Oman', flag: '🇴🇲', phoneCode: '+968' },
  { code: 'pk', name: 'Pakistan', flag: '🇵🇰', phoneCode: '+92' },
  { code: 'pw', name: 'Palau', flag: '🇵🇼', phoneCode: '+680' },
  { code: 'ps', name: 'Palestine', flag: '🇵🇸', phoneCode: '+970' },
  { code: 'pa', name: 'Panama', flag: '🇵🇦', phoneCode: '+507' },
  { code: 'pg', name: 'Papua New Guinea', flag: '🇵🇬', phoneCode: '+675' },
  { code: 'py', name: 'Paraguay', flag: '🇵🇾', phoneCode: '+595' },
  { code: 'pe', name: 'Peru', flag: '🇵🇪', phoneCode: '+51' },
  { code: 'ph', name: 'Philippines', flag: '🇵🇭', phoneCode: '+63' },
  { code: 'pl', name: 'Poland', flag: '🇵🇱', phoneCode: '+48' },
  { code: 'pt', name: 'Portugal', flag: '🇵🇹', phoneCode: '+351' },
  { code: 'qa', name: 'Qatar', flag: '🇶🇦', phoneCode: '+974' },
  { code: 'ro', name: 'Romania', flag: '🇷🇴', phoneCode: '+40' },
  { code: 'rw', name: 'Rwanda', flag: '🇷🇼', phoneCode: '+250' },
  { code: 'kn', name: 'Saint Kitts and Nevis', flag: '🇰🇳', phoneCode: '+1-869' },
  { code: 'lc', name: 'Saint Lucia', flag: '🇱🇨', phoneCode: '+1-758' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', phoneCode: '+1-784' },
  { code: 'ws', name: 'Samoa', flag: '🇼🇸', phoneCode: '+685' },
  { code: 'sm', name: 'San Marino', flag: '🇸🇲', phoneCode: '+378' },
  { code: 'st', name: 'Sao Tome and Principe', flag: '🇸🇹', phoneCode: '+239' },
  { code: 'sa', name: 'Saudi Arabia', flag: '🇸🇦', phoneCode: '+966' },
  { code: 'sn', name: 'Senegal', flag: '🇸🇳', phoneCode: '+221' },
  { code: 'rs', name: 'Serbia', flag: '🇷🇸', phoneCode: '+381' },
  { code: 'sc', name: 'Seychelles', flag: '🇸🇨', phoneCode: '+248' },
  { code: 'sl', name: 'Sierra Leone', flag: '🇸🇱', phoneCode: '+232' },
  { code: 'sg', name: 'Singapore', flag: '🇸🇬', phoneCode: '+65' },
  { code: 'sk', name: 'Slovakia', flag: '🇸🇰', phoneCode: '+421' },
  { code: 'si', name: 'Slovenia', flag: '🇸🇮', phoneCode: '+386' },
  { code: 'sb', name: 'Solomon Islands', flag: '🇸🇧', phoneCode: '+677' },
  { code: 'so', name: 'Somalia', flag: '🇸🇴', phoneCode: '+252' },
  { code: 'za', name: 'South Africa', flag: '🇿🇦', phoneCode: '+27' },
  { code: 'ss', name: 'South Sudan', flag: '🇸🇸', phoneCode: '+211' },
  { code: 'es', name: 'Spain', flag: '🇪🇸', phoneCode: '+34' },
  { code: 'lk', name: 'Sri Lanka', flag: '🇱🇰', phoneCode: '+94' },
  { code: 'sd', name: 'Sudan', flag: '🇸🇩', phoneCode: '+249' },
  { code: 'sr', name: 'Suriname', flag: '🇸🇷', phoneCode: '+597' },
  { code: 'se', name: 'Sweden', flag: '🇸🇪', phoneCode: '+46' },
  { code: 'ch', name: 'Switzerland', flag: '🇨🇭', phoneCode: '+41' },
  { code: 'sy', name: 'Syria', flag: '🇸🇾', phoneCode: '+963' },
  { code: 'tj', name: 'Tajikistan', flag: '🇹🇯', phoneCode: '+992' },
  { code: 'tz', name: 'Tanzania', flag: '🇹🇿', phoneCode: '+255' },
  { code: 'th', name: 'Thailand', flag: '🇹🇭', phoneCode: '+66' },
  { code: 'tl', name: 'Timor-Leste', flag: '🇹🇱', phoneCode: '+670' },
  { code: 'tg', name: 'Togo', flag: '🇹🇬', phoneCode: '+228' },
  { code: 'to', name: 'Tonga', flag: '🇹🇴', phoneCode: '+676' },
  { code: 'tt', name: 'Trinidad and Tobago', flag: '🇹🇹', phoneCode: '+1-868' },
  { code: 'tn', name: 'Tunisia', flag: '🇹🇳', phoneCode: '+216' },
  { code: 'tr', name: 'Turkey', flag: '🇹🇷', phoneCode: '+90' },
  { code: 'tm', name: 'Turkmenistan', flag: '🇹🇲', phoneCode: '+993' },
  { code: 'tv', name: 'Tuvalu', flag: '🇹🇻', phoneCode: '+688' },
  { code: 'ug', name: 'Uganda', flag: '🇺🇬', phoneCode: '+256' },
  { code: 'ua', name: 'Ukraine', flag: '🇺🇦', phoneCode: '+380' },
  { code: 'ae', name: 'United Arab Emirates', flag: '🇦🇪', phoneCode: '+971', abbreviation: 'UAE' },
  { code: 'gb', name: 'United Kingdom', flag: '🇬🇧', phoneCode: '+44', abbreviation: 'UK' },
  { code: 'us', name: 'United States', flag: '🇺🇸', phoneCode: '+1', abbreviation: 'USA' },
  { code: 'uy', name: 'Uruguay', flag: '🇺🇾', phoneCode: '+598' },
  { code: 'uz', name: 'Uzbekistan', flag: '🇺🇿', phoneCode: '+998' },
  { code: 'vu', name: 'Vanuatu', flag: '🇻🇺', phoneCode: '+678' },
  { code: 've', name: 'Venezuela', flag: '🇻🇪', phoneCode: '+58' },
  { code: 'vn', name: 'Vietnam', flag: '🇻🇳', phoneCode: '+84' },
  { code: 'ye', name: 'Yemen', flag: '🇾🇪', phoneCode: '+967' },
  { code: 'zm', name: 'Zambia', flag: '🇿🇲', phoneCode: '+260' },
  { code: 'zw', name: 'Zimbabwe', flag: '🇿🇼', phoneCode: '+263' },
];